[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.134.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --gc --minify --buildDrafts --buildFuture"

[context.branch-deploy]
  command = "hugo --gc --minify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

